name: docker-node-yarn
description: This GitHub Action will build your node app into a docker container
author: johnb8005
branding:
  icon: book-open
  color: purple
inputs:
  githubtoken:
    description: github token
    default: ${{ github.token }}
  nodeversion:
    description: node version
    default: 18
  container-name:
    description: name of the container
    default: ${{ github.event.repository.name }}
  build-command:
    description: build command
    default: yarn build
  message:
    description: The message to prepend the review suggestion
runs:
  using: "composite"
  steps:
    - uses: nexys-system/gh-actions-spa-test@v1.0.2
      with:
        nodeversion: ${{ inputs.nodeversion }}
        build-command: ${{ inputs.build-command }}
    - name: Set env var
      run: echo "DOCKERHUB_URL=$(echo ghcr.io/${GITHUB_REPOSITORY,,}/${{ inputs.container-name }})" >> $GITHUB_ENV
      shell: bash
    - name: Login to DockerHub Registry
      run: echo "${{ inputs.githubtoken }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      shell: bash
    - name: Create docker container
      run: docker build --build-arg GIT_SHA=$GITHUB_SHA --build-arg GIT_VERSION=${GITHUB_REF##*/} --tag $DOCKERHUB_URL:latest --tag $DOCKERHUB_URL:master --tag $DOCKERHUB_URL:${GITHUB_REF##*/} .
      shell: bash
    - name: Push Docker
      run: docker push --all-tags $DOCKERHUB_URL
      shell: bash
