name: docker-spa
description: This GitHub Action will build your vite app and turn it into a docker container
author: johnb8005
branding:
  icon: book-open
  color: purple
inputs:
  githubtoken:
    description: github token
    default: ${{ github.token }}
  message:
    description: The message to prepend the review suggestion
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v1
      with:
        node-version: 17
    - name: create httpd.conf
      run: echo "E404:index.html" > httpd.conf
      shell: bash
    - name: create docker file
      run: printf "FROM lipanski/docker-static-website:2.1.0\nCOPY httpd.conf .\nCOPY dist .\nCMD [\"/busybox\", \"httpd\", \"-f\", \"-v\", \"-p\", \"3000\", \"-c\", \"httpd.conf\"]" > Dockerfile
      shell: bash
    - run: yarn
      shell: bash
    - run: yarn test
      shell: bash
    - name: Build page
      run: VITE_VERSION=${GITHUB_REF##*/} VITE_GIT_SHA=$GITHUB_SHA yarn build
      shell: bash
    - name: Gzip
      run: gzip -r -k dist
      shell: bash
    - name: Set env var
      run: echo "DOCKERHUB_URL=$(echo ghcr.io/${GITHUB_REPOSITORY,,}/${{ github.event.repository.name }})" >> $GITHUB_ENV
      shell: bash
    - name: Login to DockerHub Registry
      run: echo "${{ inputs.githubtoken }}." | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      shell: bash
    - name: create docker container
      run: docker build --tag $DOCKERHUB_URL:latest --tag $DOCKERHUB_URL:master --tag $DOCKERHUB_URL:${GITHUB_REF##*/} .
      shell: bash
    - name: Push
      run: docker push --all-tags $DOCKERHUB_URL
      shell: bash
  
