name: Docker

on:
  push:
    tags:
      - v*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 17
      - name: create httpd.conf
        run: echo "E404:index.html" > httpd.conf
      - name: create docker file
        run: printf "FROM lipanski/docker-static-website:2.1.0\nCOPY httpd.conf .\nCOPY dist .\nCMD [\"/busybox\", \"httpd\", \"-f\", \"-v\", \"-p\", \"3000\", \"-c\", \"httpd.conf\"]" > Dockerfile
      - run: yarn
      - run: yarn test
      - name: Build page
        run: VITE_VERSION=${GITHUB_REF##*/} VITE_GIT_SHA=$GITHUB_SHA yarn build
      - name: Gzip
        run: gzip -r -k dist
      - name: Set env var
        run: echo "DOCKERHUB_URL=$(echo ghcr.io/${GITHUB_REPOSITORY,,}/${{ github.event.repository.name }})" >> $GITHUB_ENV
      - name: Login to DockerHub Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: create docker container
        run: docker build --tag $DOCKERHUB_URL:latest --tag $DOCKERHUB_URL:master --tag $DOCKERHUB_URL:${GITHUB_REF##*/} .
      - name: Push
        run: docker push --all-tags $DOCKERHUB_URL
